### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by mugli** [saif71/avro-for-chromium#2]
Thanks for taking the time to put it into a chrome extension. Will be really handy.

Two issues:
![](https://www.dropbox.com/s/gzglgjv5whdb4hq/Screenshot%202019-04-03%2013.11.35.png?raw=1)

1. The textarea is not expanding vertically up to the visible white area
2. সমুহ -> সমূহ 

Also privacy is very important to the users. Could you mention it explicitly for them that nothing they type is being sent anywhere and are being stored only in there local machine?

**Comment by saif71** [comment]
Thank you so much. Working on fixes.

**Comment by saif71** [comment]
Issues has been resolved 
Merged pull request #3 
✌🎉
